#!/usr/bin/env python
# encoding: utf-8

import sys

if __name__ == '__main__':
    if len(sys.argv) >= 3:
        if len(sys.argv) == 3:
            search_engine, keyword = sys.argv[1:3]
            page = 3
        if len(sys.argv) == 4:
            search_engine, keyword, page = sys.argv[1:4]

        if keyword == 'D': # 用D代表分类目录引擎
            keyword = None
        # DEBUG: 输出参数
        #print "search_engine:%s keyword:%s page:%s" % (search_engine, keyword, page)
        module_name = 'SE'+search_engine
        sys.path.append('./modules')
        search_engine_module = __import__(module_name)
        search_engine_class = getattr(search_engine_module, module_name)
        search_engine_class().search(keyword, page)
    else:
        print "Usage:"
        print "search (search_engine) (keyword) (page)" 
        print ""
        print "Example:"
        print "search bing shoes 3" 
        print "search amray D 50"
