#!/usr/bin/env python
# encoding: utf-8

import sys

if __name__ == '__main__':
    if len(sys.argv) == 4:
        search_engine, keyword, page = sys.argv[1:4]
        # DEBUG: 输出参数
        #print "search_engine:%s keyword:%s page:%s" % (search_engine, keyword, page)
        module_name = 'SE'+search_engine
        sys.path.append('./modules')
        search_engine_module = __import__(module_name)
        search_engine_class = getattr(search_engine_module, module_name)
        search_engine_class().search(keyword, page)
